const fs = require('fs');
const path = require('path');

const skins = [
  { id: 'genovesi_dal_negro', folder: 'genovesi', constName: 'GENOVESI_IMAGES' },
  { id: 'ramino_modiano', folder: 'ramino_modiano', constName: 'RAMINO_MODIANO_IMAGES' },
  { id: 'baroque_piatnik', folder: 'baroque_piatnik', constName: 'BAROQUE_PIATNIK_IMAGES' },
  { id: 'ancient_french', folder: 'ancient_french', constName: 'ANCIENT_FRENCH_IMAGES' },
  { id: 'lombarde_ticinesi', folder: 'lombarde_ticinesi', constName: 'LOMBARDE_TICINESI_IMAGES' },
  { id: 'russian_atlasnye', folder: 'russian_atlasnye', constName: 'RUSSIAN_ATLASNYE_IMAGES' },
  { id: 'folklore_piatnik', folder: 'folklore_piatnik', constName: 'FOLKLORE_PIATNIK_IMAGES' },
  { id: 'carta_mundi', folder: 'carta_mundi', constName: 'CARTA_MUNDI_IMAGES' },
  { id: 'kaiser_piatnik', folder: 'kaiser_piatnik', constName: 'KAISER_PIATNIK_IMAGES' },
];

const suits = ['cuori', 'denari', 'fiori', 'picche'];

let code = `// Autogenerated deck skin image registry for Cirulla
import { ImageSourcePropType } from 'react-native';
import { Card } from '../types/card';

export type DeckSkinId =
  | 'genovesi_dal_negro'
  | 'ramino_modiano'
  | 'baroque_piatnik'
  | 'ancient_french'
  | 'lombarde_ticinesi'
  | 'russian_atlasnye'
  | 'folklore_piatnik'
  | 'carta_mundi'
  | 'kaiser_piatnik'
  | 'genovesi_modiano'
  | 'napoletane_classiche'
  | 'salon_karte_66'
  | 'dondorf'
  | 'moderno'
  | 'classico_poker';

export const DEFAULT_DECK_SKIN_ID: DeckSkinId = 'genovesi_dal_negro';

`;

skins.forEach(s => {
  code += `const ${s.constName}: Record<string, ImageSourcePropType> = {\n`;
  suits.forEach(suit => {
    for (let rank = 1; rank <= 10; rank++) {
      code += `  '${suit}_${rank}': require('../../assets/cards/${s.folder}/${suit}_${rank}.png'),\n`;
    }
  });
  code += `  'back': require('../../assets/cards/${s.folder}/back.png'),\n`;
  code += `};\n\n`;
});

code += `export const BUNDLED_SKIN_MAP: Partial<Record<DeckSkinId, Record<string, ImageSourcePropType>>> = {\n`;
skins.forEach(s => {
  code += `  '${s.id}': ${s.constName},\n`;
});
code += `};\n\n`;

code += `export function getSkinCardImage(skinId: DeckSkinId | undefined, card: Card): ImageSourcePropType | null {
  const activeSkin = skinId || DEFAULT_DECK_SKIN_ID;
  const skinDeck = BUNDLED_SKIN_MAP[activeSkin] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro'];
  if (!skinDeck) return null;

  let normSuit = (card.suit || '').toLowerCase();
  if (normSuit === 'quadri') normSuit = 'denari';
  if (normSuit === 'spade' && !skinDeck['spade_1']) normSuit = 'picche';
  if (normSuit === 'coppe' && !skinDeck['coppe_1']) normSuit = 'cuori';
  if (normSuit === 'bastoni' && !skinDeck['bastoni_1']) normSuit = 'fiori';

  const key = \`\${normSuit}_\${card.rank}\`;
  return skinDeck[key] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro']?.[key] ?? null;
}

export function getSkinCardBack(skinId: DeckSkinId | undefined): ImageSourcePropType {
  const activeSkin = skinId || DEFAULT_DECK_SKIN_ID;
  const skinDeck = BUNDLED_SKIN_MAP[activeSkin] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro'];
  return skinDeck?.['back'] ?? GENOVESI_IMAGES['back'];
}
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'assets', 'deckSkinsRegistry.ts'), code, 'utf-8');
console.log('Successfully generated deckSkinsRegistry.ts with 9 bundled skins!');
