const fs = require('fs');
const path = require('path');

const availableSkins = [
  { id: 'genovesi_dal_negro', dir: 'genovesi', label: 'Genovesi (Dal Negro Treviso)' },
  { id: 'ramino_modiano', dir: 'ramino_modiano', label: 'Ramino 98 (Modiano Trieste)' },
  { id: 'baroque_piatnik', dir: 'baroque_piatnik', label: 'Baroque N. 2118 (Piatnik Vienna)' },
  { id: 'ancient_french', dir: 'ancient_french', label: 'Ancient French (Francia Antica)' },
  { id: 'lombarde_ticinesi', dir: 'lombarde_ticinesi', label: 'Lombarde - Ticinesi (Dal Negro)' },
];

const suits = ['cuori', 'denari', 'fiori', 'picche'];
const ranks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const tsLines = [
  `// Autogenerated deck skin image registry for Cirulla`,
  `import { ImageSourcePropType } from 'react-native';`,
  `import { Card } from '../types/card';`,
  ``,
  `export type DeckSkinId =`,
  `  | 'genovesi_dal_negro'`,
  `  | 'ramino_modiano'`,
  `  | 'baroque_piatnik'`,
  `  | 'ancient_french'`,
  `  | 'lombarde_ticinesi'`,
  `  | 'genovesi_modiano'`,
  `  | 'napoletane_classiche'`,
  `  | 'russian_atlasnye'`,
  `  | 'folklore_piatnik'`,
  `  | 'kaiser_piatnik'`,
  `  | 'salon_karte_66'`,
  `  | 'dondorf'`,
  `  | 'carta_mundi'`,
  `  | 'moderno'`,
  `  | 'classico_poker';`,
  ``,
  `export const DEFAULT_DECK_SKIN_ID: DeckSkinId = 'genovesi_dal_negro';`,
  ``,
];

availableSkins.forEach(s => {
  tsLines.push(`const ${s.dir.toUpperCase()}_IMAGES: Record<string, ImageSourcePropType> = {`);
  suits.forEach(suit => {
    ranks.forEach(rank => {
      const key = `${suit}_${rank}`;
      tsLines.push(`  '${key}': require('../../assets/cards/${s.dir}/${key}.png'),`);
    });
  });
  tsLines.push(`  'back': require('../../assets/cards/${s.dir}/back.png'),`);
  tsLines.push(`};`);
  tsLines.push(``);
});

tsLines.push(`export const BUNDLED_SKIN_MAP: Partial<Record<DeckSkinId, Record<string, ImageSourcePropType>>> = {`);
tsLines.push(`  'genovesi_dal_negro': GENOVESI_IMAGES,`);
tsLines.push(`  'ramino_modiano': RAMINO_MODIANO_IMAGES,`);
tsLines.push(`  'baroque_piatnik': BAROQUE_PIATNIK_IMAGES,`);
tsLines.push(`  'ancient_french': ANCIENT_FRENCH_IMAGES,`);
tsLines.push(`  'lombarde_ticinesi': LOMBARDE_TICINESI_IMAGES,`);
tsLines.push(`};`);
tsLines.push(``);

tsLines.push(`export function getSkinCardImage(skinId: DeckSkinId | undefined, card: Card): ImageSourcePropType | null {`);
tsLines.push(`  const activeSkin = skinId || DEFAULT_DECK_SKIN_ID;`);
tsLines.push(`  const skinDeck = BUNDLED_SKIN_MAP[activeSkin] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro'];`);
tsLines.push(`  if (!skinDeck) return null;`);
tsLines.push(``);
tsLines.push(`  let normSuit = (card.suit || '').toLowerCase();`);
tsLines.push(`  if (normSuit === 'quadri') normSuit = 'denari';`);
tsLines.push(`  if (normSuit === 'spade' && !skinDeck['spade_1']) normSuit = 'picche';`);
tsLines.push(`  if (normSuit === 'coppe' && !skinDeck['coppe_1']) normSuit = 'cuori';`);
tsLines.push(`  if (normSuit === 'bastoni' && !skinDeck['bastoni_1']) normSuit = 'fiori';`);
tsLines.push(``);
tsLines.push(`  const key = \`\${normSuit}_\${card.rank}\`;`);
tsLines.push(`  return skinDeck[key] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro']?.[key] ?? null;`);
tsLines.push(`}`);
tsLines.push(``);

tsLines.push(`export function getSkinCardBack(skinId: DeckSkinId | undefined): ImageSourcePropType {`);
tsLines.push(`  const activeSkin = skinId || DEFAULT_DECK_SKIN_ID;`);
tsLines.push(`  const skinDeck = BUNDLED_SKIN_MAP[activeSkin] ?? BUNDLED_SKIN_MAP['genovesi_dal_negro'];`);
tsLines.push(`  return skinDeck?.['back'] ?? GENOVESI_IMAGES['back'];`);
tsLines.push(`}`);
tsLines.push(``);

const outPath = path.join(__dirname, '..', 'src', 'assets', 'deckSkinsRegistry.ts');
fs.writeFileSync(outPath, tsLines.join('\n'));
console.log('Saved', outPath);
