// Autogenerated asset mapping for Carte Genovesi (Aisleriot Baccarat theme)
import { ImageSourcePropType } from 'react-native';
import { Card, Suit } from '../types/card';

export const GENOVESI_CARD_IMAGES: Record<string, ImageSourcePropType> = {
  'cuori_1': require('../../assets/cards/genovesi/cuori_1.png'),
  'cuori_2': require('../../assets/cards/genovesi/cuori_2.png'),
  'cuori_3': require('../../assets/cards/genovesi/cuori_3.png'),
  'cuori_4': require('../../assets/cards/genovesi/cuori_4.png'),
  'cuori_5': require('../../assets/cards/genovesi/cuori_5.png'),
  'cuori_6': require('../../assets/cards/genovesi/cuori_6.png'),
  'cuori_7': require('../../assets/cards/genovesi/cuori_7.png'),
  'cuori_8': require('../../assets/cards/genovesi/cuori_8.png'),
  'cuori_9': require('../../assets/cards/genovesi/cuori_9.png'),
  'cuori_10': require('../../assets/cards/genovesi/cuori_10.png'),
  'denari_1': require('../../assets/cards/genovesi/denari_1.png'),
  'denari_2': require('../../assets/cards/genovesi/denari_2.png'),
  'denari_3': require('../../assets/cards/genovesi/denari_3.png'),
  'denari_4': require('../../assets/cards/genovesi/denari_4.png'),
  'denari_5': require('../../assets/cards/genovesi/denari_5.png'),
  'denari_6': require('../../assets/cards/genovesi/denari_6.png'),
  'denari_7': require('../../assets/cards/genovesi/denari_7.png'),
  'denari_8': require('../../assets/cards/genovesi/denari_8.png'),
  'denari_9': require('../../assets/cards/genovesi/denari_9.png'),
  'denari_10': require('../../assets/cards/genovesi/denari_10.png'),
  'fiori_1': require('../../assets/cards/genovesi/fiori_1.png'),
  'fiori_2': require('../../assets/cards/genovesi/fiori_2.png'),
  'fiori_3': require('../../assets/cards/genovesi/fiori_3.png'),
  'fiori_4': require('../../assets/cards/genovesi/fiori_4.png'),
  'fiori_5': require('../../assets/cards/genovesi/fiori_5.png'),
  'fiori_6': require('../../assets/cards/genovesi/fiori_6.png'),
  'fiori_7': require('../../assets/cards/genovesi/fiori_7.png'),
  'fiori_8': require('../../assets/cards/genovesi/fiori_8.png'),
  'fiori_9': require('../../assets/cards/genovesi/fiori_9.png'),
  'fiori_10': require('../../assets/cards/genovesi/fiori_10.png'),
  'picche_1': require('../../assets/cards/genovesi/picche_1.png'),
  'picche_2': require('../../assets/cards/genovesi/picche_2.png'),
  'picche_3': require('../../assets/cards/genovesi/picche_3.png'),
  'picche_4': require('../../assets/cards/genovesi/picche_4.png'),
  'picche_5': require('../../assets/cards/genovesi/picche_5.png'),
  'picche_6': require('../../assets/cards/genovesi/picche_6.png'),
  'picche_7': require('../../assets/cards/genovesi/picche_7.png'),
  'picche_8': require('../../assets/cards/genovesi/picche_8.png'),
  'picche_9': require('../../assets/cards/genovesi/picche_9.png'),
  'picche_10': require('../../assets/cards/genovesi/picche_10.png'),
  'back': require('../../assets/cards/genovesi/back.png'),
};

export function getGenovesiCardImage(card: Card): ImageSourcePropType | null {
  let normSuit = (card.suit || '').toLowerCase();
  if (normSuit === 'quadri') normSuit = 'denari';
  const key = `${normSuit}_${card.rank}`;
  return GENOVESI_CARD_IMAGES[key] ?? null;
}

export function getGenovesiCardBack(): ImageSourcePropType {
  return GENOVESI_CARD_IMAGES['back'];
}
